### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by andyduke** [modulovalue/dart_intersperse#4]
Null safety is at a stable stage and it's therefore time to start migrating packages as per the dart [migration guide](https://dart.dev/null-safety/migration-guide).

**Comment by ghost** [comment]
I am removing the package from my project because I want to migrate to null safety

**Comment by dumazy** [comment]
I submitted a PR for this: #5

**Comment by modulovalue** [comment]
Thanks @dumazy

(I've changed the bound to a beta version, I don't think that should cause any problems and it should count as null safe where that counts.
This is for people who can't or haven't updated to 2.12.0 yet)

**Comment by dumazy** [comment]
Thanks for accepting the PR so fast. Could you elaborate why the beta version of Dart 2.12 would allow for a better adoption? I think the constraints are the same. Also, if this is a major update to 2.0.0, breaking changes can be expected

**Comment by modulovalue** [comment]
> Could you elaborate why the beta version of Dart 2.12 I think the constraints are the same

I'm using a Flutter fork that is based on a dart beta version. I can't update right now.
2.12.0 as the lower constraint would never resolve for me on that beta version.

That version has NNBD so I expect none of the tooling to say that this package isn't null safe (I guess we'll have to see what the analysis results on pub.dev have to say about that)
